
package com.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonServiceCRUD", targetNamespace = "http://soap.com/", wsdlLocation = "http://0.0.0.0:8080/PersonServiceCRUD?wsdl")
public class PersonServiceCRUD
    extends Service
{

    private final static URL PERSONSERVICECRUD_WSDL_LOCATION;
    private final static WebServiceException PERSONSERVICECRUD_EXCEPTION;
    private final static QName PERSONSERVICECRUD_QNAME = new QName("http://soap.com/", "PersonServiceCRUD");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://0.0.0.0:8080/PersonServiceCRUD?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSERVICECRUD_WSDL_LOCATION = url;
        PERSONSERVICECRUD_EXCEPTION = e;
    }

    public PersonServiceCRUD() {
        super(__getWsdlLocation(), PERSONSERVICECRUD_QNAME);
    }

    public PersonServiceCRUD(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSERVICECRUD_QNAME, features);
    }

    public PersonServiceCRUD(URL wsdlLocation) {
        super(wsdlLocation, PERSONSERVICECRUD_QNAME);
    }

    public PersonServiceCRUD(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSERVICECRUD_QNAME, features);
    }

    public PersonServiceCRUD(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceCRUD(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonWebService
     */
    @WebEndpoint(name = "PersonWebServicePort")
    public PersonWebService getPersonWebServicePort() {
        return super.getPort(new QName("http://soap.com/", "PersonWebServicePort"), PersonWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonWebService
     */
    @WebEndpoint(name = "PersonWebServicePort")
    public PersonWebService getPersonWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.com/", "PersonWebServicePort"), PersonWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSERVICECRUD_EXCEPTION!= null) {
            throw PERSONSERVICECRUD_EXCEPTION;
        }
        return PERSONSERVICECRUD_WSDL_LOCATION;
    }

}
